Adding a scheduled task which can be activated to remove non-approved/deleted questions completely.
frankkoch/moodle-mod_studentquiz pull request #281
Opened 2020-10-23 07:19 UTC by Clyxz

Fixes issue 255: Adding a scheduled task which can be activated to remove non-approved/deleted questions completely.
Currently non approved and deleted questions will be included for removal.

2020-10-29 16:04 UTC, dionysius commented
The CI check failing part comes from master, fixed in https://github.com/frankkoch/moodle-mod_studentquiz/commit/72e62901097cb13baaf6fb711ac2fcf890bb14a5. No need to merge master again, just as a note here

2020-11-05 14:51 UTC, dionysius requested changes

2020-11-05 15:35 UTC, Clyxz commented on classes/task/delete_orphaned_questions.php
> +
I added a try-catch transaction block around these parts.

2020-11-05 15:36 UTC, Clyxz commented on settings.php
> +    $settings->add(new admin_setting_configselect('studentquiz/deleteorphanedtimelimit',
There is indeed a duration field for administration settings. I added this instead of the dropdown menu.

2020-11-06 11:44 UTC, merged

2020-11-06 11:45 UTC, dionysius commented
Thank you very much for the contribution! :tada: